# Generated by Django 5.0.6 on 2026-01-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playtest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playtestaccount",
            name="utc_offset",
            field=models.SmallIntegerField(default=0),
        ),
    ]
