# Generated by Django 5.0.6 on 2026-02-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playtest", "0002_playtestaccount_utc_offset"),
    ]

    operations = [
        migrations.AddField(
            model_name="playtestaccount",
            name="recent_scores",
            field=models.JSONField(default=list),
        ),
    ]
