# Generated by Django 5.0.6 on 2026-02-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playtest", "0003_playtestaccount_recent_scores"),
    ]

    operations = [
        migrations.AddField(
            model_name="playtestaccount",
            name="response_data",
            field=models.BinaryField(default=b""),
        ),
    ]
