# Generated by Django 4.2.2 on 2024-07-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="tags",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
    ]
