# Generated by Django 5.0.6 on 2024-10-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0003_achievementcompletionplacement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievementcompletionplacement",
            name="place",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
