# Generated by Django 5.0.6 on 2024-10-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0004_achievementcompletionplacement_place"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="achievementcompletion",
            constraint=models.UniqueConstraint(
                fields=("player", "achievement"), name="unique_achievement"
            ),
        ),
    ]
