# Generated by Django 5.0.6 on 2024-10-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0005_achievementcompletion_unique_achievement"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="audio",
            field=models.CharField(default=""),
        ),
    ]
