# Generated by Django 5.0.6 on 2024-11-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0007_alter_achievement_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievement",
            name="name",
            field=models.CharField(max_length=128),
        ),
    ]
