# Generated by Django 5.0.6 on 2024-11-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0008_alter_achievement_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="team_admin",
            field=models.BooleanField(default=False),
        ),
    ]
