# Generated by Django 5.0.6 on 2024-12-24 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0011_remove_achievement_votes_achievementvote"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="achievement",
            name="category",
        ),
        migrations.AddField(
            model_name="achievement",
            name="creator",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="achievement",
            name="solution",
            field=models.CharField(default="", max_length=2048),
            preserve_default=False,
        ),
    ]
