# Generated by Django 5.0.6 on 2025-03-15 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "achievements",
            "0012_remove_achievement_category_achievement_creator_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="achievementcomment",
            name="posted_at",
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 15, 1, 49, 59, 555928)),
            preserve_default=False,
        ),
    ]
