# Generated by Django 5.0.6 on 2025-03-16 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0013_achievementcomment_posted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 3, 16, 14, 34, 53, 726161)
            ),
            preserve_default=False,
        ),
    ]
