# Generated by Django 5.0.6 on 2025-03-16 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0014_achievement_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="last_edited",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 3, 16, 18, 37, 23, 481910, tzinfo=datetime.timezone.utc)
            ),
            preserve_default=False,
        ),
    ]
