# Generated by Django 5.0.6 on 2025-03-18 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0016_rename_last_edited_achievement_last_edited_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="AchievementBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("release_time", models.DateTimeField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventIteration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="achievement",
            name="batch",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="achievements.achievementbatch",
            ),
        ),
        migrations.AddField(
            model_name="achievementbatch",
            name="iteration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="achievements.eventiteration",
            ),
        ),
    ]
