# Generated by Django 5.0.6 on 2025-03-18 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "achievements",
            "0017_achievementbatch_eventiteration_achievement_batch_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="iteration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="achievements.eventiteration",
            ),
        ),
    ]
