# Generated by Django 5.0.6 on 2025-03-19 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0019_beatmapconnection"),
    ]

    operations = [
        migrations.RenameField(
            model_name="beatmapconnection",
            old_name="beatmap",
            new_name="info",
        ),
    ]
