# Generated by Django 5.0.6 on 2025-04-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0020_rename_beatmap_beatmapconnection_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventiteration",
            name="description",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="eventiteration",
            name="name",
            field=models.CharField(default="", max_length=64),
        ),
    ]
