# Generated by Django 5.0.6 on 2025-04-17 07:08

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0021_eventiteration_description_eventiteration_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventiteration",
            name="registration_end",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 4, 17, 7, 8, 32, 474779, tzinfo=datetime.timezone.utc)
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_screened", models.BooleanField()),
                (
                    "iteration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="achievements.eventiteration",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
