# Generated by Django 5.0.6 on 2025-05-22 03:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0022_eventiteration_registration_end_registration"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventiteration",
            name="registration_closes",
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 21, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eventiteration",
            name="registration_opens",
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 21, 0, 0)),
            preserve_default=False,
        ),
    ]
