# Generated by Django 5.0.6 on 2025-05-22 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0023_eventiteration_registration_closes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventiteration",
            name="registration_closes",
        ),
        migrations.RemoveField(
            model_name="eventiteration",
            name="registration_opens",
        ),
    ]
