# Generated by Django 5.0.6 on 2025-05-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0024_remove_eventiteration_registration_closes_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.UniqueConstraint(fields=("user", "iteration"), name="unique_registration"),
        ),
    ]
