# Generated by Django 5.0.6 on 2025-05-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0025_registration_unique_registration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="is_screened",
            field=models.BooleanField(default=False),
        ),
    ]
