# Generated by Django 5.0.6 on 2025-05-24 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0022_chatmessage"),
        ("achievements", "0025_registration_unique_registration"),
    ]

    operations = []
