# Generated by Django 5.0.6 on 2025-05-24 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0026_merge_20250524_0301"),
        ("achievements", "0027_announcement"),
    ]

    operations = []
