# Generated by Django 5.0.6 on 2025-05-24 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0028_merge_0026_merge_20250524_0301_0027_announcement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="iteration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="achievements.eventiteration",
            ),
        ),
    ]
