# Generated by Django 5.0.6 on 2025-05-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0029_alter_team_iteration"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="is_free_agent",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="team",
            name="accepts_free_agents",
            field=models.BooleanField(default=False),
        ),
    ]
