# Generated by Django 5.0.6 on 2025-05-26 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0031_teaminvite_teaminvite_unique_team_invite"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="invite",
        ),
    ]
