# Generated by Django 5.0.6 on 2025-05-31 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0032_remove_team_invite"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventiteration",
            name="banner",
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="hidden_points",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
