# Generated by Django 5.0.6 on 2025-05-31 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0033_eventiteration_banner_team_hidden_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievementcompletion",
            name="time_placement",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
