# Generated by Django 5.0.6 on 2025-06-07 02:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0034_achievementcompletion_time_placement"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventiteration",
            name="registration_start",
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 1, 0, 0, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
