# Generated by Django 5.0.6 on 2025-06-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0035_eventiteration_registration_start"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventiteration",
            name="registration_start",
        ),
        migrations.AddField(
            model_name="eventiteration",
            name="registration_open",
            field=models.BooleanField(default=False),
        ),
    ]
