# Generated by Django 5.0.6 on 2025-06-07 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0036_remove_eventiteration_registration_start_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventiteration",
            name="description",
            field=models.JSONField(default=list),
        ),
    ]
