# Generated by Django 5.0.6 on 2025-06-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0037_alter_eventiteration_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="anonymous_name",
            field=models.CharField(default="", max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=32),
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(fields=("name", "iteration_id"), name="unique_iteration_team_name"),
        ),
    ]
