# Generated by Django 5.0.6 on 2025-06-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0038_team_anonymous_name_alter_team_name_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                fields=("anonymous_name", "iteration_id"),
                name="unique_iteration_anon_team_name",
            ),
        ),
    ]
