# Generated by Django 5.0.6 on 2025-06-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0039_team_unique_iteration_anon_team_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventiteration",
            name="faq",
            field=models.JSONField(default=list),
        ),
    ]
