# Generated by Django 5.0.6 on 2025-06-29 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0040_eventiteration_faq"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="hidden_points",
            new_name="frozen_points",
        ),
    ]
