# Generated by Django 5.0.6 on 2025-07-06 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0041_rename_hidden_points_team_frozen_points"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="frozen_points",
        ),
    ]
