# Generated by Django 5.0.6 on 2025-07-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0042_remove_team_frozen_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=32),
        ),
    ]
