# Generated by Django 5.0.6 on 2025-07-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0043_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="is_desc",
            field=models.BooleanField(default=True),
        ),
    ]
