# Generated by Django 5.0.6 on 2025-07-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0044_achievement_is_desc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="achievement",
            name="beatmap",
        ),
        migrations.RemoveField(
            model_name="achievement",
            name="release_time",
        ),
        migrations.AddField(
            model_name="achievement",
            name="completion_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
