# Generated by Django 5.0.6 on 2025-07-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0045_remove_achievement_beatmap_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="worth_points",
            field=models.BooleanField(default=True),
        ),
    ]
