# Generated by Django 5.0.6 on 2025-07-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0046_achievement_worth_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventiteration",
            name="solutions_released",
            field=models.BooleanField(default=False),
        ),
    ]
