# Generated by Django 5.0.6 on 2025-11-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0047_eventiteration_solutions_released"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="solution_algorithm",
            field=models.JSONField(default=dict),
        ),
    ]
