# Generated by Django 5.0.6 on 2026-02-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0048_achievement_solution_algorithm"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="algorithm_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
