# Generated by Django 5.0.6 on 2026-02-20 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0049_achievement_algorithm_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievementcomment",
            name="channel",
            field=models.SmallIntegerField(default=0),
        ),
    ]
