# Generated by Django 5.0.6 on 2026-02-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0050_achievementcomment_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievementcomment",
            name="deleted_at",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="achievementcomment",
            name="edited_at",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
