# Generated by Django 5.0.6 on 2026-02-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0051_achievementcomment_deleted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="staff_solved",
            field=models.BooleanField(default=False),
        ),
    ]
