# Generated by Django 5.2.11 on 2026-03-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0052_achievement_staff_solved"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="algorithm_code",
            field=models.TextField(default=""),
        ),
    ]
