# Generated by Django 5.2.11 on 2026-04-09 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0053_achievement_algorithm_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="achievement",
            name="algorithm_code",
        ),
    ]
