# Generated by Django 5.2.11 on 2026-05-29 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0054_remove_achievement_algorithm_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="icon",
        ),
        migrations.AddField(
            model_name="registration",
            name="free_agent_type",
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="registration",
            name="is_free_agent",
            field=models.BooleanField(default=False),
        ),
    ]
