# Generated by Django 5.2.11 on 2026-05-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0055_remove_team_icon_registration_free_agent_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="free_agent_type",
            field=models.SmallIntegerField(default=1),
        ),
    ]
