# Generated by Django 5.2.11 on 2026-06-19 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0056_team_free_agent_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="avg_difficulty_rating",
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="achievement",
            name="avg_quality_rating",
            field=models.FloatField(default=None, null=True),
        ),
        migrations.CreateModel(
            name="AchievementRating",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("upvoted", models.BooleanField(default=False)),
                ("quality", models.PositiveSmallIntegerField(default=None, null=True)),
                ("difficulty", models.PositiveSmallIntegerField(default=None, null=True)),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="achievements.achievement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="ratings", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
