# Generated by Django 5.2.11 on 2026-06-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0057_achievement_avg_difficulty_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="upvotes",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="AchievementVote",
        ),
    ]
