# Generated by Django 5.2.11 on 2026-06-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0058_achievement_upvotes_delete_achievementvote"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="solution_parts",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="achievementcompletion",
            name="extra",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="achievementcompletion",
            name="is_complete",
            field=models.BooleanField(default=True),
        ),
    ]
